name: scrape

on:
  schedule:
    - cron: '45 8 * * *'
  workflow_dispatch:

jobs:
  scrape-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install project
        run: yarn
      - name: Run main script
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}
          SENDER_EMAIL_USERNAME: ${{ secrets.SENDER_EMAIL_USERNAME }}
          SENDER_EMAIL_PASSWORD: ${{ secrets.SENDER_EMAIL_PASSWORD }}
          RECEIVER_EMAIL_USERNAME: ${{ secrets.RECEIVER_EMAIL_USERNAME }}
        run: node index.js
